[build]
  command = "npm run build"
  publish = "public/"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
package = "@netlify/plugin-sitemap"
